export const portfolioProjects = [
  {
    id: "mamola",
    name: "مامولا",
    nameEn: "Mamola",
    cover: "/portfolio/mamola-logo.webp",
    category: "حلويات ومخبوزات",
    statement: "علامة دافئة تبدأ من الاسم، وتستمر في المكان والمنتج وكل لحظة يلتقي فيها العميل بها.",
    story: "بدأ المشروع ببناء شخصية مألوفة ودافئة، ثم صياغة اسم مامولا وتصميم العلامة وخطها الخاص. امتد النظام من العبوات والمنتجات إلى الديكور الداخلي والحملات، ليحافظ الحضور على النبرة نفسها في كل تطبيق.",
    scope: [
      "شخصية العلامة",
      "تسمية العلامة",
      "صناعة العلامة",
      "الخطوط الطباعية",
      "الاستشارات الإبداعية",
    ],
    consulting: ["الديكور الداخلي", "الحملات الإعلانية"],
    palette: { surface: "#ead5c5", ink: "#6f431f", accent: "#a86b38" },
    gallery: [
      { src: "/portfolio/mamola-hero.webp", alt: "التجربة البصرية لعلامة مامولا", layout: "wide" },
      { src: "/portfolio/mamola-products.webp", alt: "منتجات مامولا ضمن نظام العلامة", layout: "tall" },
      { src: "/portfolio/mamola-interior.webp", alt: "التوجيه الإبداعي للديكور الداخلي في مامولا", layout: "standard" },
      { src: "/portfolio/mamola-packaging.webp", alt: "تطبيقات تغليف مامولا", layout: "standard" },
    ],
  },
  {
    id: "spices-palace",
    name: "قصر التوابل",
    nameEn: "Spices Palace",
    cover: "/portfolio/spices-logo.webp",
    category: "تطوير علامة ومنتجات",
    statement: "تطوير يحفظ ما يعرفه الناس عن العلامة، ويمنحها نظاماً أوضح للمنتجات والحضور اليومي.",
    story: "لم يبدأ العمل من الشعار، بل من دراسة العلامة القائمة وما يحتاج إلى التطوير. أُعيد بناء الشخصية والعلامة والنظام الطباعي، ثم انتقل العمل إلى المنتجات والتغليف والمركبات والحملات والبروفايل التعريفي والمحتوى التسويقي.",
    scope: [
      "دراسة التطوير",
      "شخصية العلامة",
      "صناعة العلامة",
      "الخطوط الطباعية",
      "تصميم المنتجات",
      "الاستشارات الإبداعية",
    ],
    consulting: ["البروفايل التعريفي", "المحتوى التسويقي"],
    palette: { surface: "#f2f0e8", ink: "#302c27", accent: "#f47721" },
    gallery: [
      { src: "/portfolio/spices-hero.webp", alt: "نظام قصر التوابل بعد التطوير", layout: "wide" },
      { src: "/portfolio/spices-pack.webp", alt: "تصميم منتجات وتغليف قصر التوابل", layout: "tall" },
      { src: "/portfolio/spices-van.webp", alt: "تطبيق هوية قصر التوابل على المركبات", layout: "standard" },
      { src: "/portfolio/spices-billboard.webp", alt: "حملة قصر التوابل الإعلانية", layout: "standard" },
    ],
  },
  {
    id: "bukhary-akhtar",
    name: "بخاري أختر",
    nameEn: "Bukhary Akhtr",
    cover: "/portfolio/bukhary-logo.webp",
    category: "مطاعم",
    statement: "هوية شعبية نابضة، تستلهم تفاصيل تجربة البخاري وتحوّلها إلى لغة مرئية متماسكة.",
    story: "بُنيت شخصية بخاري أختر لتكون مباشرة وحيوية، ثم صُممت العلامة والخط الطباعي الخاص بها. ظهر النظام في الواجهات والملصقات والقوائم والمواد التحريرية، مع مفردات لونية ورسومية يسهل تمييزها.",
    scope: ["شخصية العلامة", "صناعة العلامة", "الخطوط الطباعية"],
    consulting: [],
    palette: { surface: "#49acd3", ink: "#c82237", accent: "#f3d73b" },
    gallery: [
      { src: "/portfolio/bukhary-hero.webp", alt: "النظام البصري لبخاري أختر", layout: "wide" },
      { src: "/portfolio/bukhary-store.webp", alt: "واجهة مطعم بخاري أختر", layout: "tall" },
      { src: "/portfolio/bukhary-posters.webp", alt: "ملصقات بخاري أختر", layout: "standard" },
      { src: "/portfolio/bukhary-editorial.webp", alt: "التطبيقات التحريرية لبخاري أختر", layout: "standard" },
      { src: "/portfolio/bukhary-billboard.webp", alt: "لوحة إعلانية لبخاري أختر", layout: "wide" },
    ],
  },
  {
    id: "asnaf",
    name: "أصناف",
    nameEn: "Asnaf",
    cover: "/portfolio/asnaf-logo.webp",
    category: "تطوير علامة",
    statement: "إعادة بناء علامة قائمة لتصبح أخف حضوراً وأكثر قدرة على الامتداد عبر الفروع والتطبيقات.",
    story: "بدأ المشروع بدراسة العلامة قبل التطوير، ثم بناء شخصية جديدة وصناعة العلامة بصرياً. امتد النظام إلى الواجهة والمطبوعات والزي والمواد التعريفية، ضمن عائلة لونية تحافظ على الألفة وتمنح العلامة حضوراً متجدداً.",
    scope: ["دراسة التطوير", "شخصية العلامة", "صناعة العلامة"],
    consulting: [],
    palette: { surface: "#f1dde7", ink: "#744fa0", accent: "#d87d98" },
    gallery: [
      { src: "/portfolio/asnaf-hero.webp", alt: "هوية أصناف بعد التطوير", layout: "wide" },
      { src: "/portfolio/asnaf-uniform.webp", alt: "تطبيق هوية أصناف على الزي", layout: "tall" },
      { src: "/portfolio/asnaf-stationery.webp", alt: "مطبوعات أصناف", layout: "tall" },
      { src: "/portfolio/asnaf-packaging.webp", alt: "تطبيقات تغليف أصناف", layout: "standard" },
    ],
  },
  {
    id: "yart",
    name: "يارت",
    nameEn: "Yart",
    cover: "/portfolio/yart-logo.webp",
    category: "مخبوزات حرفية",
    statement: "علامة مخبوزات حرفية مرنة وبسيطة، لها حضور واضح من العبوة إلى المكان.",
    story: "صُممت شخصية يارت وعلامتها لتعبّرا عن مخبوزات حرفية معاصرة من دون تكلّف. انتقلت اللغة البصرية إلى الأكواب والعبوات والزي والديكور، وصاحبها بروفايل تعريفي يحفظ نبرة العلامة.",
    scope: ["شخصية العلامة", "صناعة العلامة", "الاستشارات الإبداعية"],
    consulting: ["البروفايل التعريفي"],
    palette: { surface: "#df7d6c", ink: "#f5d122", accent: "#5b322e" },
    gallery: [
      { src: "/portfolio/yart-hero.webp", alt: "العالم البصري ليارت", layout: "wide" },
      { src: "/portfolio/yart-pastry.webp", alt: "تطبيقات يارت على المنتجات", layout: "standard" },
      { src: "/portfolio/yart-cup.webp", alt: "كوب يارت ضمن نظام العلامة", layout: "tall" },
      { src: "/portfolio/yart-interior.webp", alt: "تطبيق علامة يارت في المكان", layout: "tall" },
    ],
  },
  {
    id: "mandi-majeed",
    name: "مندي مجيد",
    nameEn: "Mandi Majeed",
    cover: "/portfolio/mandi-logo.webp",
    category: "تطوير علامة مطاعم",
    statement: "شخصية واضحة لتجربة المندي، تجمع حرارة المنتج مع بساطة علامة يسهل تذكرها.",
    story: "بدأ تطوير مندي مجيد بدراسة العلامة القائمة ثم إعادة بناء شخصيتها وعلامتها. تشكل النظام حول حضور كتابي واضح ولون قوي، وامتد إلى عبوات الوجبات والصناديق وتقديم المنتج.",
    scope: ["دراسة التطوير", "شخصية العلامة", "صناعة العلامة"],
    consulting: [],
    palette: { surface: "#fa681f", ink: "#fff7e9", accent: "#5b2413" },
    gallery: [
      { src: "/portfolio/mandi-hero.webp", alt: "هوية مندي مجيد", layout: "wide" },
      { src: "/portfolio/mandi-meal.webp", alt: "تطبيق العلامة على تقديم وجبة مندي مجيد", layout: "standard" },
      { src: "/portfolio/mandi-packaging.webp", alt: "تغليف مندي مجيد", layout: "tall" },
      { src: "/portfolio/mandi-boxes.webp", alt: "صناديق مندي مجيد", layout: "standard" },
    ],
  },
  {
    id: "shshay",
    name: "ششاي",
    nameEn: "Shshay",
    cover: "/portfolio/tashkeela-logo.webp",
    category: "مشروبات",
    statement: "علامة شاي مرحة ومباشرة، تتحرك بسهولة بين الكوب والعبوة والمركبة والمكان.",
    story: "بُنيت شخصية ششاي حول تجربة قريبة وخفيفة، ثم تحولت إلى علامة ونظام رسومي ذي حركة واضحة. ظهر النظام على الأكواب والأكياس والزي والمركبة مع احتفاظه بالشخصية نفسها في كل نقطة تماس.",
    scope: ["شخصية العلامة", "صناعة العلامة"],
    consulting: [],
    palette: { surface: "#b8d8bf", ink: "#56316f", accent: "#f06e82" },
    gallery: [
      { src: "/portfolio/tashkeela-hero.webp", alt: "العالم البصري لعلامة ششاي", layout: "wide" },
      { src: "/portfolio/tashkeela-van.webp", alt: "تطبيق ششاي على المركبة", layout: "wide" },
      { src: "/portfolio/tashkeela-bags.webp", alt: "أكياس ششاي", layout: "standard" },
      { src: "/portfolio/tashkeela-cup.webp", alt: "كوب ششاي", layout: "standard" },
    ],
  },
];
